services:
  fastapi:
    image: asia-south1-docker.pkg.dev/linux-box-1-492217/capstone-registry/fastapi:51
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    networks:
      - my-net
    restart: unless-stopped

  django:
    image: asia-south1-docker.pkg.dev/linux-box-1-492217/capstone-registry/django:51
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    networks:
      - my-net
    restart: unless-stopped

  node:
    image: asia-south1-docker.pkg.dev/linux-box-1-492217/capstone-registry/node:51
    ports:
      - "8002:8002"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    networks:
      - my-net
    restart: unless-stopped

  dotnet:
    image: asia-south1-docker.pkg.dev/linux-box-1-492217/capstone-registry/dotnet:51
    ports:
      - "8003:8003"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    networks:
      - my-net
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
      - django
      - node
      - dotnet
    networks:
      - my-net
    restart: unless-stopped

networks:
  my-net:
    driver: bridge