{
 "title": "Capstone Monitoring",
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode='idle'}[2m])) * 100)",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "Memory %"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~'fastapi|django|node|dotnet|nginx'})",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode='idle'}[2m])) * 100)",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Memory Usage Over Time",
   "type": "graph",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "Memory %"
    }
   ]
  }
 ]
}