server {
    listen 80;

    # FastAPI
    location /fastapi/ {
        proxy_pass http://fastapi-app:8000/;
    }

    # Django
    location /django/ {
        proxy_pass http://django-app:8001/;
    }

    # Node
    location /node/ {
        proxy_pass http://node-app:8002/;
    }

    # .NET
    location /dotnet/ {
        proxy_pass http://dotnet-app:8003/;
    }
}